language: node_js

node_js:
  - "4.1.1"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  - npm run test.coveralls

env:
  - COVERALLS_REPO_TOKEN=ZdPzOJnP7AQgvpXanYDMEQQ4EUKnxoBfh